export const AGENT_TEAM = [
  {
    id: 'agent-1',
    name: 'Customer Support AI',
    role: 'Support Lead & Resolution Specialist',
    department: 'Customer Support',
    status: 'online', // 'online' | 'busy' | 'offline'
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    color: '#0ea5e9',
    rating: 4.9,
    reviewsCount: 342,
    price: '$49/mo',
    tasksHandled: 1420,
    satisfactionScore: 98,
    responseTime: '< 15s',
    accuracy: '99.4%',
    description: 'Handles customer inquiries, ticketing, live chat responses, and refund automation 24/7.',
    capabilities: ['Ticketing & Email', 'Live Chat', 'Refund Processing', 'FAQ Resolution'],
    category: 'Support',
    badge: 'Popular',
    featured: true,
  },
  {
    id: 'agent-2',
    name: 'Sales Development AI',
    role: 'Lead Qualifier & Outbound Specialist',
    department: 'Sales',
    status: 'online',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    color: '#14b8a6',
    rating: 4.8,
    reviewsCount: 289,
    price: '$79/mo',
    tasksHandled: 980,
    satisfactionScore: 96,
    responseTime: '1 min',
    accuracy: '97.8%',
    description: 'Qualifies incoming leads, schedules demos, runs email outreach campaigns, and updates CRM pipeline.',
    capabilities: ['Lead Qualification', 'Demo Scheduling', 'Email Outreach', 'HubSpot / Salesforce Sync'],
    category: 'Sales',
    badge: 'Trending',
    featured: true,
  },
  {
    id: 'agent-3',
    name: 'Marketing Strategist AI',
    role: 'Content & Social Growth Manager',
    department: 'Marketing',
    status: 'busy',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    color: '#8b5cf6',
    rating: 4.9,
    reviewsCount: 412,
    price: '$69/mo',
    tasksHandled: 2150,
    satisfactionScore: 99,
    responseTime: '30s',
    accuracy: '98.9%',
    description: 'Generates SEO articles, social media posts, email newsletters, and ad copy optimized for conversions.',
    capabilities: ['SEO Writing', 'Social Media Scheduling', 'Ad Copy Creation', 'Campaign Analytics'],
    category: 'Marketing',
    badge: 'Top Rated',
    featured: true,
  },
  {
    id: 'agent-4',
    name: 'Finance & Accounts AI',
    role: 'Bookkeeper & Invoice Auditor',
    department: 'Finance',
    status: 'online',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    color: '#10b981',
    rating: 5.0,
    reviewsCount: 195,
    price: '$89/mo',
    tasksHandled: 3400,
    satisfactionScore: 100,
    responseTime: 'Instant',
    accuracy: '99.9%',
    description: 'Automates expense categorization, invoice generation, tax estimations, and cash flow reports.',
    capabilities: ['QuickBooks Sync', 'Invoice Processing', 'Tax Estimate Calculation', 'Cash Flow Reports'],
    category: 'Finance',
    badge: 'Essential',
    featured: true,
  },
  {
    id: 'agent-5',
    name: 'HR & Onboarding AI',
    role: 'Talent Acquisition & Employee Ops',
    department: 'HR',
    status: 'offline',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
    color: '#f59e0b',
    rating: 4.7,
    reviewsCount: 128,
    price: '$59/mo',
    tasksHandled: 640,
    satisfactionScore: 95,
    responseTime: '2 mins',
    accuracy: '96.5%',
    description: 'Screens resumes, schedules candidate interviews, manages employee docs, and tracks leave requests.',
    capabilities: ['Resume Screening', 'Interview Scheduling', 'Onboarding Guides', 'Leave Management'],
    category: 'HR',
    badge: 'New',
    featured: false,
  },
  {
    id: 'agent-6',
    name: 'Operations & Workflow AI',
    role: 'Process Coordinator & Automation Specialist',
    department: 'Operations',
    status: 'online',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    color: '#ec4899',
    rating: 4.9,
    reviewsCount: 310,
    price: '$75/mo',
    tasksHandled: 4800,
    satisfactionScore: 98,
    responseTime: '< 5s',
    accuracy: '99.2%',
    description: 'Monitors cross-functional workflows, sends internal reminders, tracks project milestones, and alerts bottlenecks.',
    capabilities: ['Workflow Triggering', 'Zapier Integration', 'Milestone Alerts', 'Resource Tracking'],
    category: 'Operations',
    badge: 'Featured',
    featured: true,
  },
  {
    id: 'agent-7',
    name: 'Legal & Compliance AI',
    role: 'Contract Reviewer & Risk Auditor',
    department: 'Legal',
    status: 'busy',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=250&q=80',
    color: '#6366f1',
    rating: 4.9,
    reviewsCount: 167,
    price: '$99/mo',
    tasksHandled: 520,
    satisfactionScore: 97,
    responseTime: '45s',
    accuracy: '99.7%',
    description: 'Reviews NDAs, flags non-standard contract clauses, tracks compliance deadlines, and drafts standard terms.',
    capabilities: ['NDA Review', 'Clause Risk Audit', 'GDPR/CCPA Compliance', 'Document Drafting'],
    category: 'Legal',
    badge: 'Pro',
    featured: false,
  },
  {
    id: 'agent-8',
    name: 'Data Analyst & Insights AI',
    role: 'BI Reporting & Predictive Modeler',
    department: 'Analytics',
    status: 'online',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    color: '#3b82f6',
    rating: 4.8,
    reviewsCount: 224,
    price: '$65/mo',
    tasksHandled: 1890,
    satisfactionScore: 97,
    responseTime: '10s',
    accuracy: '98.5%',
    description: 'Aggregates sales data, predicts churn rates, generates weekly executive executive summaries and KPI dashboards.',
    capabilities: ['Churn Prediction', 'Executive Reporting', 'Cohort Analysis', 'SQL Querying'],
    category: 'Analytics',
    badge: 'Popular',
    featured: false,
  }
]

export const DASHBOARD_STATS = [
  {
    id: 'active-agents',
    title: 'Active AI Agents',
    value: '6 / 8',
    change: '+2 this week',
    isPositive: true,
    icon: 'Bot',
    color: 'from-blue-600 to-teal-500',
    subtitle: '75% operational capacity',
  },
  {
    id: 'tasks-completed',
    title: 'Tasks Automated',
    value: '14,790',
    change: '+18.4%',
    isPositive: true,
    icon: 'CheckCircle2',
    color: 'from-teal-500 to-emerald-500',
    subtitle: 'Saved 340+ manual hours',
  },
  {
    id: 'monthly-revenue',
    title: 'Est. Cost Savings',
    value: '$12,450',
    change: '+$2,100 vs last month',
    isPositive: true,
    icon: 'DollarSign',
    color: 'from-indigo-600 to-blue-500',
    subtitle: 'ROI: 8.4x platform cost',
  },
  {
    id: 'avg-response',
    title: 'Avg. Response Time',
    value: '14.2s',
    change: '-3.1s faster',
    isPositive: true,
    icon: 'Zap',
    color: 'from-amber-500 to-orange-500',
    subtitle: '99.8% uptime maintained',
  },
]

export const RECENT_ACTIVITIES = [
  {
    id: 'act-1',
    agentName: 'Customer Support AI',
    agentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    action: 'Resolved customer ticket #4812 with refund recommendation',
    timestamp: '2 minutes ago',
    type: 'success',
    badge: 'Support',
  },
  {
    id: 'act-2',
    agentName: 'Finance & Accounts AI',
    agentAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    action: 'Reconciled 42 transactions in QuickBooks and flagged $120 variance',
    timestamp: '14 minutes ago',
    type: 'info',
    badge: 'Finance',
  },
  {
    id: 'act-3',
    agentName: 'Marketing Strategist AI',
    agentAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    action: 'Published weekly blog newsletter and scheduled 5 Twitter posts',
    timestamp: '1 hour ago',
    type: 'success',
    badge: 'Marketing',
  },
  {
    id: 'act-4',
    agentName: 'Sales Development AI',
    agentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    action: 'Qualified enterprise lead "Acme Corp" & booked demo for Thursday',
    timestamp: '3 hours ago',
    type: 'success',
    badge: 'Sales',
  },
  {
    id: 'act-5',
    agentName: 'Operations & Workflow AI',
    agentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    action: 'Automated weekly staff rota sync between Google Calendar & Slack',
    timestamp: '5 hours ago',
    type: 'info',
    badge: 'Operations',
  },
]

export const WEEKLY_PERFORMANCE = [
  { day: 'Mon', tasks: 1820, hoursSaved: 42, revenue: 1420 },
  { day: 'Tue', tasks: 2450, hoursSaved: 56, revenue: 1890 },
  { day: 'Wed', tasks: 2100, hoursSaved: 48, revenue: 1650 },
  { day: 'Thu', tasks: 2980, hoursSaved: 68, revenue: 2310 },
  { day: 'Fri', tasks: 3120, hoursSaved: 72, revenue: 2450 },
  { day: 'Sat', tasks: 1250, hoursSaved: 28, revenue: 980 },
  { day: 'Sun', tasks: 1070, hoursSaved: 24, revenue: 750 },
]

export const NOTIFICATIONS = [
  {
    id: 'n-1',
    title: 'New High Priority Lead',
    message: 'Sales AI qualified Apex Tech ($50k ARR potential). Demo scheduled.',
    time: '10m ago',
    unread: true,
  },
  {
    id: 'n-2',
    title: 'Weekly Finance Summary',
    message: 'Finance AI saved $420 in duplicate subscription audits.',
    time: '1h ago',
    unread: true,
  },
  {
    id: 'n-3',
    title: 'Agent Hire Successful',
    message: 'Operations & Workflow AI deployed and active on your workflow grid.',
    time: '1 day ago',
    unread: false,
  },
]
